"""Measure how the RAM engine scales on a pedigree-shaped model, and record where it hurts.

    python scripts/scale_ram.py [max_generations]

Regenerates `docs/scale_ram.md`. The model is `tests/battery.py::lineage` -- a lineage at
assortative-mating equilibrium: a founding individual and their partner, then one child per
generation who takes an outside partner. Seven to ten nodes per generation, which is roughly the
shape the pedigree unroller generates, so the timings transfer.

The model is imported from the battery rather than defined here, so that it gets two-engine
agreement coverage and so its substantive correctness (the lineal-relative result, equilibrium
self-consistency, the mate correlation) is asserted by `tests/test_am_lineage.py` on every test
run rather than only when someone regenerates this report. Note how assortment is represented,
because it is not the obvious way: see `docs/assortment_representation_trap.md`.
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

import sympy as sp

import pathmgr as pm

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT / "tests") not in sys.path:
    sys.path.insert(0, str(ROOT / "tests"))

from battery import lineage  # noqa: E402 -- needs the sys.path line above


def profile(max_generations: int) -> list[dict]:
    rows = []
    for depth in range(1, max_generations + 1):
        model = lineage(depth)
        engine = pm.RAMEngine(model)

        start = time.perf_counter()
        sigma = engine.sigma()
        build = time.perf_counter() - start

        entry_ops = [
            sp.count_ops(sigma[i, j]) for i in range(sigma.rows) for j in range(sigma.cols)
        ]

        start = time.perf_counter()
        engine.cov("y_0m", f"y_{depth}c")
        query = time.perf_counter() - start

        start = time.perf_counter()
        engine.cov("y_0m", f"y_{depth}c", form="simplified")
        simplified = time.perf_counter() - start

        rows.append(
            {
                "depth": depth,
                "nodes": len(model.names),
                "build_s": build,
                "query_s": query,
                "simplify_s": simplified,
                "total_ops": sum(entry_ops),
                "worst_entry_ops": max(entry_ops, default=0),
            }
        )
        r = rows[-1]
        print(
            f"  depth {r['depth']:3d}  nodes {r['nodes']:4d}  build {r['build_s']:8.3f}s  "
            f"query {r['query_s']:7.4f}s  simplified {r['simplify_s']:8.3f}s  "
            f"ops {r['total_ops']:8d}  worst {r['worst_entry_ops']:6d}"
        )
    return rows


def write_report(rows: list[dict]) -> Path:
    out = ROOT / "docs" / "scale_ram.md"
    out.parent.mkdir(exist_ok=True)
    lines = [
        "# RAM engine scale",
        "",
        "Generated by `python scripts/scale_ram.py N`. Re-run after any change to how",
        "`Sigma` is built. These numbers are the budget task-20260804-151350 works within when",
        "it unrolls generations.",
        "",
        "**Model**: `tests/battery.py::lineage` -- a lineage at assortative-mating equilibrium, a",
        "founding couple then one child per generation who takes an outside partner. Its",
        "correctness is asserted by `tests/test_am_lineage.py` (the lineal-relative result of",
        "`relative_covariance.tex` at every depth, equilibrium self-consistency, and partners",
        "correlating at `rho_y`), not here -- so these timings are taken from a model the test",
        "suite checks on every run. **How assortment is encoded is the subtle part:** see",
        "[assortment_representation_trap.md](assortment_representation_trap.md).",
        "",
        "| generations | nodes | build Sigma | cov() query | cov(form='simplified') | total ops in Sigma | worst entry |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['depth']} | {r['nodes']} | {r['build_s']:.3f}s | {r['query_s']:.4f}s | "
            f"{r['simplify_s']:.3f}s | {r['total_ops']} | {r['worst_entry_ops']} |"
        )
    comfortable = [r for r in rows if r["build_s"] < 3.0]
    painful = [r for r in rows if r["build_s"] >= 10.0]
    lines += [
        "",
        "## Where it starts to hurt",
        "",
        f"- Comfortable to **{max((r['depth'] for r in comfortable), default=0)} generations**"
        f" ({max((r['nodes'] for r in comfortable), default=0)} nodes): building Sigma stays"
        f" under 3 s.",
    ]
    if painful:
        first = min(r["depth"] for r in painful)
        lines.append(
            f"- Past **{first} generations** the build crosses 10 s and climbs steeply"
            f" (depth {rows[-1]['depth']}: {rows[-1]['build_s']:.0f} s)."
        )
    else:
        lines.append(
            f"- No depth measured here crossed 10 s (deepest:"
            f" {rows[-1]['depth']} generations at {rows[-1]['build_s']:.1f} s)."
        )
    lines += [
        "- Queries stay free at every depth, because Sigma is built once and cached.",
        "- If a future task needs materially more depth, the optimisation to reach for is a",
        "  **targeted single-entry computation**: `cov(x, y)` currently forces the whole",
        "  n-by-n Sigma, but the two recursions only need the ancestors of `x` and `y`. That",
        "  is not implemented -- the full matrix is the primary object by design -- and the",
        "  numbers above suggest it is not yet needed.",
        "",
        "## Reading it",
        "",
        "- **Building `Sigma` dominates; querying it is free.** `cov()` is a matrix lookup plus",
        "  post-processing, so the build cost is paid once per `model.revision` and then cached.",
        "- **`form='simplified'` is the expensive knob, not the engine.** That is why `cov()`",
        "  defaults to `'expanded'` and `simplify` is never called automatically.",
        "- Total ops in `Sigma` grows roughly with the square of the node count, because there",
        "  are `n^2` entries and each stays small. The worst single entry is what to watch: if",
        "  it starts growing with depth rather than plateauing, expansion has stopped cancelling",
        "  and that is the onset of real symbolic blowup.",
        "",
        "## Guidance for unrolling generations",
        "",
        "- Prefer **one model holding all generations** over many small ones: `Sigma` is cached",
        "  per `model.revision`, so a single build answers every cross-generation query. Mutating",
        "  the model invalidates the cache and pays the build again -- so build the whole",
        "  pedigree, then query it.",
        "- Keep coefficients symbolic and substitute numbers **at the end**, on the one scalar",
        "  expression you care about, rather than building a numeric model per parameter value.",
        "- When depth becomes the binding constraint, that is the signal to stop unrolling and",
        "  solve the equilibrium fixed point instead -- which is task-20260804-151351, and why",
        '  "unroll a lot" is not a substitute for it.',
        "",
        "## The assortment-representation trap",
        "",
        "The trap this model exists to avoid -- a bidirected edge on an endogenous genetic value,",
        "which yields a non-PSD `Sigma` silently -- was found while writing this profile, but it is",
        "hand-written prose and no longer lives in this generated file. It is",
        "[assortment_representation_trap.md](assortment_representation_trap.md), which is the most",
        "important document in the repository.",
        "",
    ]
    out.write_text("\n".join(lines))
    return out


if __name__ == "__main__":
    limit = int(sys.argv[1]) if len(sys.argv) > 1 else 12
    print("correctness of the lineage model: `pytest tests/test_am_lineage.py`")
    print(f"profiling lineage models up to {limit} generations")
    report = write_report(profile(limit))
    print(f"wrote {report.relative_to(ROOT)}")
